export const ORDER_STATE_FULL_OPTIONS = [
    {id: "1", color: "#34209E", name: "En attente du paiement par chèque"},
    {id: "2", color: "#3498D8", name: "Paiement accepté"},
    {id: "3", color: "#3498D8", name: "En cours de préparation"},
    {id: "4", color: "#01B887", name: "Expédié"},
    {id: "5", color: "#01B887", name: "Livré"},
    {id: "6", color: "#2C3E50", name: "Annulé"},
    {id: "7", color: "#01B887", name: "Remboursé"},
    {id: "8", color: "#E74C3C", name: "Erreur de paiement"},
    {id: "9", color: "#3498D8", name: "En attente de réapprovisionnement (payé)"},
    {id: "10", color: "#34209E", name: "En attente de virement bancaire"},
    {id: "11", color: "#3498D8", name: "Paiement à distance accepté"},
    {id: "12", color: "#34209E", name: "En attente de réapprovisionnement (non payé)"},
    {id: "13", color: "#34209E", name: "En attente de paiement à la livraison"},
    {id: "14", color: "#34209E", name: "En attente de paiement"},
    {id: "15", color: "#01B887", name: "Remboursement partiel"},
    {id: "16", color: "#3498D8", name: "Paiement partiel"},
    {id: "17", color: "#3498D8", name: "Autorisation. A capturer par le marchand"},
];